package com.coressoft.breader.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.coressoft.breader.bean.ChapterName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAPTER_NAME".
*/
public class ChapterNameDao extends AbstractDao<ChapterName, Void> {

    public static final String TABLENAME = "CHAPTER_NAME";

    /**
     * Properties of entity ChapterName.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", false, "ID");
        public final static Property Chapter = new Property(1, String.class, "chapter", false, "CHAPTER");
        public final static Property ChapterName = new Property(2, String.class, "chapterName", false, "CHAPTER_NAME");
    }


    public ChapterNameDao(DaoConfig config) {
        super(config);
    }
    
    public ChapterNameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAPTER_NAME\" (" + //
                "\"ID\" INTEGER NOT NULL ," + // 0: id
                "\"CHAPTER\" TEXT," + // 1: chapter
                "\"CHAPTER_NAME\" TEXT);"); // 2: chapterName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAPTER_NAME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChapterName entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindString(2, chapter);
        }
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(3, chapterName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChapterName entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindString(2, chapter);
        }
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(3, chapterName);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ChapterName readEntity(Cursor cursor, int offset) {
        ChapterName entity = new ChapterName( //
            cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // chapter
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // chapterName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChapterName entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setChapter(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setChapterName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ChapterName entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ChapterName entity) {
        return null;
    }

    @Override
    public boolean hasKey(ChapterName entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
