package com.coressoft.breader.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.coressoft.breader.bean.Verse;
import com.coressoft.breader.bean.Note;
import com.coressoft.breader.bean.Book;
import com.coressoft.breader.bean.ChapterName;
import com.coressoft.breader.bean.Marks;

import com.coressoft.breader.db.VerseDao;
import com.coressoft.breader.db.NoteDao;
import com.coressoft.breader.db.BookDao;
import com.coressoft.breader.db.ChapterNameDao;
import com.coressoft.breader.db.MarksDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig verseDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig bookDaoConfig;
    private final DaoConfig chapterNameDaoConfig;
    private final DaoConfig marksDaoConfig;

    private final VerseDao verseDao;
    private final NoteDao noteDao;
    private final BookDao bookDao;
    private final ChapterNameDao chapterNameDao;
    private final MarksDao marksDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        verseDaoConfig = daoConfigMap.get(VerseDao.class).clone();
        verseDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        chapterNameDaoConfig = daoConfigMap.get(ChapterNameDao.class).clone();
        chapterNameDaoConfig.initIdentityScope(type);

        marksDaoConfig = daoConfigMap.get(MarksDao.class).clone();
        marksDaoConfig.initIdentityScope(type);

        verseDao = new VerseDao(verseDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);
        chapterNameDao = new ChapterNameDao(chapterNameDaoConfig, this);
        marksDao = new MarksDao(marksDaoConfig, this);

        registerDao(Verse.class, verseDao);
        registerDao(Note.class, noteDao);
        registerDao(Book.class, bookDao);
        registerDao(ChapterName.class, chapterNameDao);
        registerDao(Marks.class, marksDao);
    }
    
    public void clear() {
        verseDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        bookDaoConfig.clearIdentityScope();
        chapterNameDaoConfig.clearIdentityScope();
        marksDaoConfig.clearIdentityScope();
    }

    public VerseDao getVerseDao() {
        return verseDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public ChapterNameDao getChapterNameDao() {
        return chapterNameDao;
    }

    public MarksDao getMarksDao() {
        return marksDao;
    }

}
